### ISSUE TITLE
Choose a device by default

### ISSUE THREAD

**Issue by jme783** [spark/particle-dev#103]
When trying to compile firmware on Dev, the user is forced to select a device manually to ensure compiling works properly. If a device is not selected, the user will receive compiling errors that are not related to issues with their firmware, but simply a lack of a device to build for.

For instance,

<img width="293" alt="screen shot 2015-08-04 at 2 17 07 pm" src="https://cloud.githubusercontent.com/assets/4605360/9073673/cdc66794-3ab7-11e5-9bc4-d609689b1cec.png">

Instead, when Particle Dev opens, we should select the last-flashed device by default. If there isn't a last-flashed device, sort by whether the device is online and choose the first one as a default

**Comment by suda** [comment]
Fixed with https://github.com/spark/particle-dev/releases/tag/v0.1.18
