### ISSUE TITLE
build didn't produce binary Error: Command Failed

### ISSUE THREAD

**Issue by hwbrill** [spark/particle-dev#149]
This indication shows after I select 'compile in cloud and show any errors if any' button.  There were no compile errors.

**Comment by suda** [comment]
@hwbrill can you share a screen shot of Dev right after it fails?

**Comment by hwbrill** [comment]
Prior to 'Compile to cloud and show any errrors'
![compile_error1](https://cloud.githubusercontent.com/assets/12366286/15858482/58aa0c10-2c86-11e6-87ad-b2eefb46383a.jpg)

After the 'Compile to cloud and show any errors'
![compile_error2](https://cloud.githubusercontent.com/assets/12366286/15858483/58abca96-2c86-11e6-8078-298f18c9b9e5.jpg)

**Comment by suda** [comment]
It looks like you have the whole library opened in Dev which it will try to compile as it doesn't compile just the opened tab but the whole directory. Currently [there is no direct way to use libraries](https://github.com/spark/particle-dev/issues/71) in Dev and you would need to [follow these instructions](https://docs.particle.io/guide/tools-and-features/dev/#using-community-libraries) to use them.

**Comment by hwbrill** [comment]
I've also have been fooling around with my library's file structure and found that each code file, *.ino, must be in a folder by it's self for the cloud compile to succeed.  I knew about the firmware, to be in same directory as the *.ino file but, I didn't see anything about not having other code files in the same directory during compile...
