### ISSUE TITLE
Latest Atom will not Rebuild Package

### ISSUE THREAD

**Issue by kleerkoat** [spark/particle-dev#152]
getting the following when trying to rebuild package with Atom 1.9.0:

```
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
gyp ERR! build error 
```

**Comment by suda** [comment]
It looks like `node-serialport` would require an update. Thx!

**Comment by suda** [comment]
The core error here is `apm` bundled with Atom. Current Atom version (1.9.8) is using older apm (1.10.0). There is a fix in [apm 1.12.6](https://github.com/atom/apm/commit/a5d467635d19a0f6ed998d1a5749f50121522a79) but even Atom beta (1.10.0-beta5) is using slightly older version. So I hope this will be fixed in newer Atom beta.

As for temporary workaround you can install the package using command line:
```
export npm_config_runtime=electron
apm install particle-dev
```

**Comment by Magnus512** [comment]
I got this 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.37.8
node-pre-gyp ERR! stack     at get_runtime_abi (/home/marcus/.atom/packages/particle-dev/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/marcus/.atom/packages/particle-dev/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:277:19)
node-pre-gyp ERR! stack     at install (/home/marcus/.atom/packages/particle-dev/node_modules/serialport/node_modules/node-pre-gyp/lib/install.js:148:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/home/marcus/.atom/packages/particle-dev/node_modules/serialport/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/home/marcus/.atom/packages/particle-dev/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/marcus/.atom/packages/particle-dev/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Linux 4.7.1-040701-generic
node-pre-gyp ERR! command "node" "/home/marcus/.atom/packages/particle-dev/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/marcus/.atom/packages/particle-dev/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 

npm ERR! Linux 4.7.1-040701-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/marcus/.atom/.apm/.apmrc" "--userconfig" "/home/marcus/.atom/.apmrc" "rebuild" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! serialport@4.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/marcus/.atom/packages/particle-dev/npm-debug.log

**Comment by suda** [comment]
@Magnus512 I tried this on my Elementary (Ubuntu) VM and seems to work. Have you run both `export` and `apm install` in terminal?

**Comment by Magnus512** [comment]
@suda yes, well, I'm going to try again removing all packages,

**Comment by Magnus512** [comment]
![terminal](https://cloud.githubusercontent.com/assets/7065012/17859914/a8a237da-6848-11e6-8ffc-779bd6d47c7f.png)
Everything seems to be ok. but when I open atom I get something like this
![bug](https://cloud.githubusercontent.com/assets/7065012/17859987/f225f5f4-6848-11e6-8d56-e3be454f27a2.png)
![error](https://cloud.githubusercontent.com/assets/7065012/17859990/f47d8d58-6848-11e6-9a3b-74e202e352d9.png)

Jajajaja I got this now :+1:  thanks

**Comment by kleerkoat** [comment]
@Magnus512 OT with this post, what status line plugin are you using in zsh?

**Comment by Magnus512** [comment]
@kleerkoat itś powerline :)
