### ISSUE TITLE
ATOM Error immediately after installing particle-dev ver 0.1.3

### ISSUE THREAD

**Issue by a33nitsuj** [spark/particle-dev#156]
Error compiling Less stylesheet:
.../.atom/packages/particle-dev/styles/particle-dev.less
Line number: 8
'utilities.less' wasn't found
Failed to load the particle-dev package
'utilities.less' wasn't found in /home/justin/.atom/packages/particle-dev/styles/particle-dev.less:8:0
Hide Stack Trace
LessError: 'utilities.less' wasn't found
  at /home/<user>/.atom/packages/particle-dev/styles/particle-dev.less:8:0
The error was thrown from the particle-dev package. You can help by creating an issue. Please explain what actions triggered this error.
This occurred immediately after installing particle-dev ver 0.1.3

**Comment by kleerkoat** [comment]
same here...

`**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [particle-dev](https://github.com/spark/particle-dev) package, v0.1.3


### Stack Trace

Failed to load the particle-dev package

```
At 'utilities.less' wasn't found in /Users/rgilmore/.atom/packages/particle-dev/styles/particle-dev.less:8:0

LessError: 'utilities.less' wasn't found
  at /Users/rgilmore/.atom/packages/particle-dev/styles/particle-dev.less:8:0`

**Comment by suda** [comment]
Oh it looks like One theme doesn't have `utilities.less` file. You can avoid this error by switching to Atom  Dark/Light theme for now.

**Comment by kleerkoat** [comment]
is this an issue with particle-dev or the atom one themes? should it be reported to them instead?

**Comment by suda** [comment]
It's particle-dev issue. We need to remove the dependency on the `utilities.less` file.

**Comment by brencerddwr** [comment]
I was having this problem and changed the theme in Atom from "One Dark"(default) to "Atom Dark"(mentioned in particle-dev.less file) and it installed without a problem.
