### ISSUE TITLE
Ubuntu Support

### ISSUE THREAD

**Issue by jravetch** [spark/particle-dev#16]
Would be great to have a deb package for Ubuntu

**Comment by jravetch** [comment]
@suda Any update on native Ubuntu pkg?

**Comment by adomenech73** [comment]
Interested on that too ,or in a way to compile it on Linux

**Comment by lightx** [comment]
would be great

**Comment by suda** [comment]
There is no Linux support yet but seeing the interest, I could try to tackle it after upgrading Dev to Atom 1.0 API.

**Comment by aceperry** [comment]
Cool, been waiting patiently.  Just wanted to let you know that there is still interest out there for deb/linux version.

**Comment by zsup** [comment]
@aceperry sorry for the delay, upgrading to Atom 1.0 had some unexpected roadblocks, and @suda's on vacation now; we'll get back to this in a couple of weeks, hopefully

**Comment by adomenech73** [comment]
Any advance on this?? 
I tried to compile, even on the Dockerized environment, but the mac script gives me some:
hdiutil: command not found &
ditto: command not found
that don't seem trivial to bypass

Can anyone upgrade the workaround to compile it on linux? this would be a great feature in future releases, I would like to use it in my favorite SO. Thank's for anyone efforts!!

**Comment by suda** [comment]
@adomenech73 commands you mentioned are used by the [package-app](https://github.com/spark/spark-dev/blob/master/build/tasks/package-app.coffee) task. You can try commenting it out in [Gruntfile.coffee](https://github.com/spark/spark-dev/blob/master/build/Gruntfile.coffee#L79).

**Comment by adomenech73** [comment]
Thank's @suda
finally I could compile perfectly, cloning git repository as it is and moving to v0.0.23 to avoid a "generate-module-cache" task error. So I did

git fetch
git checkout v0.0.23
script/build

and everything finished with a 
Running "install" task
Done, without errors.

**Comment by adomenech73** [comment]
Actually I'm watching messages like:

[12087:0726/123401:INFO:CONSOLE(114)] "Fetching local packages failed.", source: /home/albert/Projects/Electronics/Spark/spark-dev/dist/linux/Particle Dev/resources/app/node_modules/settings-view/lib/main.js (114)
[12087:0726/124249:INFO:CONSOLE(285)] "Fetching local packages failed.", source: /home/albert/Projects/Electronics/Spark/spark-dev/dist/linux/Particle Dev/resources/app/node_modules/settings-view/lib/installed-packages-panel.js (285)

On the startup and packages view. Also updates functionality seems to freeze
Is there any post-install task, that I need to do?

**Comment by suda** [comment]
@adomenech73 `master` was in a non build-able state. I've just fixed it with d6d344b37deebcded2024094960ca53372706029
Can you try it now?

**Comment by adomenech73** [comment]
@suda Now it's just perfect!!
I was wondering why there was not possible to access to the device functions from the ide
I solved package manager thing making a copy of apm on node_modules but the ide was not complete at all.

Thank's, really appreciated!

**Comment by suda** [comment]
Instructions for using Particle Dev packages on Linux have been added to readme: https://github.com/spark/spark-dev#linux

**Comment by suda** [comment]
Particle Dev package does not work on Linux. Only thing needed now would be packaging thus I'm closing this one in favor of [Build Linux packages #14](https://github.com/spark/particle-dev-app/issues/14)
