### ISSUE TITLE
Char behavior doesn't match reference docs

### ISSUE THREAD

**Issue by Rukkh** [spark/particle-dev#161]
The reference docs are very clear that chars are signed and permit arithmetic:
https://docs.particle.io/reference/firmware/photon/#data-types

But when using the local Particle IDE and the cloud compiler, they appear to be unsigned. 

Suggest update compiler commands (if possible on platform)  to reflect docs. 
( Or change docs to note limitations )

More details here: 
https://community.particle.io/t/chars-not-behaving-as-expected-unsigned-in-particle-dev-tool-cloud-compiler/26439

I took a bit of a stab at which repo to raise this against, sorry if I missed.

**Comment by suda** [comment]
Thanks for raising this! The correct repo should be one with [documentation](https://github.com/spark/docs). I'm going to close this issue but could you open it in the correct repo?
