### ISSUE TITLE
Case Sensitivity 0.1.13

### ISSUE THREAD

**Issue by magnum129** [spark/particle-dev#172]
I'm on Fedora with Atom 1.12.7 and Particle Dev 0.1.13, I keep getting errors about missing libraries when attempting to cloud compile. It appears since the latest update everything is forced to lowercase:

The path the files looks more like: /home/joeUser/Desktop/900MHZ_Particle_Weatherstation/OneWire/OneWire.h

But instead this seems to be where it's looking:
/home/joeuser/desktop/900mhz_particle_weatherstation/onewire/onewire.h'

More stacktrace:

900mhz_particle_weatherstation
onewire
RFM69-Particle
spark-dallas-temperature
SparkFun_Photon_Weather_Shield_Library
weatherStation.ino
weatherStation.ino
1
1

 
ClearConsole
weatherStation.ino1:1TheOutdoorWeatherManPhoton
LFUTF-8C++
Uncaught Error: ENOENT: no such file or directory, stat '/home/joeuser/desktop/900mhz_particle_weatherstation/onewire/onewire.h'
/home/joeUser/.atom/packages/particle-dev/node_modules/particle-library-manager/dist/librepo_fs.js:1233
Hide Stack Trace
Error: ENOENT: no such file or directory, stat '/home/joeUser/desktop/900mhz_particle_weatherstation/onewire/onewire.h'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at normalizeAndSplitPath (/home/joeUser/.atom/packages/particle-dev/node_modules/particle-library-manager/dist/librepo_fs.js:1168:16)
    at Object.pathsCommonPrefix (/home/joeUser/.atom/packages/particle-dev/node_modules/particle-library-manager/dist/librepo_fs.js:1220:17)
    at Object.mapCommonPrefix (/home/joeUser/.atom/packages/particle-dev/lib/main.coffee:596:20)
    at /home/joeUser/.atom/packages/particle-dev/lib/main.coffee:630:41
    at Object.loginRequired (/home/joeUser/.atom/packages/particle-dev/lib/main.coffee:300:5)
    at Object.compileCloud (/home/joeUser/.atom/packages/particle-dev/lib/main.coffee:604:65)
    at atom-workspace.<anonymous> (/home/joeUser/.atom/packages/particle-dev/lib/main.coffee:83:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at executeCallback (/home/joeUser/.atom/packages/tool-bar/lib/tool-bar-button-view.js:105:19)
    at ToolBarButtonView._onClick (/home/joeUser/.atom/packages/tool-bar/lib/tool-bar-button-view.js:69:7)
The error was thrown from the particle-dev package. You can help by creating an issue. Please explain what actions triggered this error.
Create issue on the particle-dev package

**Comment by magnum129** [comment]
If I rename all of the includes to lowercase it seems to be happy, despite the includes that actually require each other and have the expected path name in the .h file... Like the OneWire and dallas temp probe...

**Comment by ybizeul** [comment]
I'm surprised this bug isn't getting more attention. Can't compile anything since some update.
![screen shot 2017-01-01 at 12 30 39 am](https://cloud.githubusercontent.com/assets/182035/21580304/8b2295dc-cfb9-11e6-932b-a4b36dbd979a.PNG)

**Comment by ybizeul** [comment]
edit your `~/.atom/packages/particle-dev/node_modules/particle-library-manager/dist/librepo_fs.js`

Line 1166, remove the lowerCase call, to make it like this :
```
	var abs = path.resolve(cwd, p); // this might be a bit heavy handed on POSIX...
```

Yeah, you bet it might be __heavy handed on POSIX...__

**Comment by magnum129** [comment]
Thanks @ybizeul, that works. I'm guessing most people are using the cloud version, haven't upgraded, or are not on  *nix... and haven't noticed.

**Comment by ybizeul** [comment]
thats weird indeed. Maybe we should switch to local compiler!

**Comment by ybizeul** [comment]
https://github.com/spark/particle-library-manager/commit/97193e3b9d225da0166d722a9e74b017d76bfd2c It's apparently  in the library, good news!

**Comment by tsayles** [comment]
I also ran into this on Linux Mint 18 with Atom 1.12.7

librepo_fs.js edit from @ybizeul seems to have fixed the problem. 

Steps to reproduce:

1. Open Atom and update all pending spark/Particle* packages;
2. git pull https://github.com/snovalleypa/SVPA-FloodSensor-2016.git dev
   _or clone_
3. Open with ./firmware folder with ATOM
4. Open SVPA-FloodSensor-2016.ino and select Particle --> Compile in the Could from the menu.


**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Linux Mint
**Thrown From**: [particle-dev](https://github.com/spark/particle-dev) package, v0.1.13


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/home/tsayles/dropbox/projects/openhardware/svpa-floodsensor-2016/firmware/checkupdateota.h'

```
At /home/tsayles/.atom/packages/particle-dev/node_modules/particle-library-manager/dist/librepo_fs.js:1233

Error: ENOENT: no such file or directory, stat '/home/tsayles/dropbox/projects/openhardware/svpa-floodsensor-2016/firmware/checkupdateota.h'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at normalizeAndSplitPath (/home/tsayles/.atom/packages/particle-dev/node_modules/particle-library-manager/dist/librepo_fs.js:1168:16)
    at Object.pathsCommonPrefix (/home/tsayles/.atom/packages/particle-dev/node_modules/particle-library-manager/dist/librepo_fs.js:1220:17)
    at Object.mapCommonPrefix (/home/tsayles/.atom/packages/particle-dev/lib/main.coffee:596:20)
    at /home/tsayles/.atom/packages/particle-dev/lib/main.coffee:630:41
    at Object.loginRequired (/home/tsayles/.atom/packages/particle-dev/lib/main.coffee:300:5)
    at Object.compileCloud (/home/tsayles/.atom/packages/particle-dev/lib/main.coffee:604:65)
    at atom-workspace.<anonymous> (/home/tsayles/.atom/packages/particle-dev/lib/main.coffee:83:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1136:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -3:47.6.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always)
     -3:47.6.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always)
     -3:46.8.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:46.7.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:46.7.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:46.7.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:51.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:50.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:48.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:20.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:55.5.0 particle-dev:compile-cloud (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "particle-dev-libraries"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
console-panel, v0.2.1 (active)
language-particle, v0.3.4 (active)
particle-dev, v0.1.13 (active)
particle-dev-cloud-functions, v0.1.0 (active)
particle-dev-cloud-variables, v0.1.0 (active)
particle-dev-libraries, v0.2.11 (inactive)
particle-dev-profiles, v0.1.11 (active)
particle-dev-release-notes, v0.53.2 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by suda** [comment]
@magnum129 @ybizeul @tsayles just relased v0.1.14 which should fix this issue :)
