### ISSUE TITLE
Compile target does not automatically change when Core devices are selected

### ISSUE THREAD

**Issue by brandoaire** [spark/particle-dev#177]
When you select a Photon, Electron, or Raspberry Pi device in the device selector, the compile target indicated at the bottom status bar changes to the corresponding platform.

That is **not** the case when you select Cores from the device selector, originally submitted in the community thread and confirmed on my machine.

https://community.particle.io/t/new-desktop-ide/28800

**Comment by suda** [comment]
Fixed with https://github.com/spark/particle-dev/commit/738e019228da2b50922d1d946c4b090b474d18e9
