### ISSUE TITLE
[Web IDE] Libraries can't be removed from project

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-dev#180]
Since I can't find a repo for Build I file this issue here.

I've got a big project that had some legacy libraries included, but with 0.6.1-rc.2 one of these is broken and I'd need to replace it with a new version, but I seem to be unable to remove any of them

![image](https://cloud.githubusercontent.com/assets/6604878/22302313/7acd7656-e32e-11e6-8373-ac4225ef8c94.png)

**Comment by christinestamper** [comment]
I have had this same problem. I tried Firefox, IE and Chrome. I finally was able to fiddle around in Chrome enough to delete a library. In firefox, sometimes the X didn't show up, same thing in IE. Even when it did, if you point to it to click, a hint text box comes up and blocks the button. In chrome, after some fiddling, I was able to delete. However, I'm hoping for a fix to this soon.

**Comment by GregSawin** [comment]
Same issue, can you say what kind of fiddling you did to be able to remove a library?

**Comment by ScruffR** [comment]
I was able to do it with FireFox on a highres screen where the fonts were smaller in comparison to the width of the side bar.

**Comment by GregSawin** [comment]
I tried shrinking and zooming with no success.  I don't see a more info popup like some have which simply cover the X, it's not showing at all.  I'm tired of waiting so I'm just going to create a new project and copy/paste everything over :(

**Comment by suda** [comment]
This has been logged in closed issue tracker for Build
