### ISSUE TITLE
NeoGPS library is not being detected as a library

### ISSUE THREAD

**Issue by jenesaisdiq** [spark/particle-dev#188]
Currently have it open, it has a library.properties, examples, src, but the toolbar is not giving me the publish options. Try downloading it from spark/NeoGPS-particle.

**Comment by jenesaisdiq** [comment]
CLI is more illuminating:
```
Helium:neoGPS-particle dick$ particle library upload
Library is not valid. LICENSE is missing
main source is missing
main header is missing
```

**Comment by suda** [comment]
We removed the **Upload** and **Publish** buttons from the toolbar. When issuing the command from palette or library management panel an error about validation errors is being shown.
