### ISSUE TITLE
Compiler error messages not showing in desktop IDE

### ISSUE THREAD

**Issue by 4ULjPwGBOC33N** [spark/particle-dev#203]
Compile the test program below (note typo for "void" )in the desktop IDE (atom 1.15.0, particle-dev 0.1.20, particle-dev-cloud-functions 0.1.0)

Select "Compile in the cloud". The IDE suppresses the error message and instead returns "Success" in the status bar.

Compile in the web IDE and the compile errors are correctly reported

```
int led2=D7;
Void setup(){
  pinMode(led2,OUTPUT);
}
void loop(){
  digitalWrite(led2,HIGH);
  delay(1000);
  digitalWrite(led2,LOW);
  delay(2000); 
}
```

**Comment by suda** [comment]
Hello, I'm unable to reproduce the issue:
![screen shot 2017-03-31 at 12 30 52](https://cloud.githubusercontent.com/assets/25722/24548815/6902d566-160e-11e7-8800-530b3554b66d.png)

What's the directory structure of your project?

**Comment by 4ULjPwGBOC33N** [comment]
![screen shot 2017-03-31 at 3 59 08 pm](https://cloud.githubusercontent.com/assets/26288599/24572147/1a16c4a4-162b-11e7-9cd9-24ce08f3ba80.jpg)

**Comment by 4ULjPwGBOC33N** [comment]
Found the problem. Compile is looking at Test.ino (which has stubs but no link to Test.cpp) , code is in test.cpp.  Is there a compile switch so that I can use regular C++ file structure ?

**Comment by suda** [comment]
If you have both `.ino` file and `.cpp` file in your `src` directory, both will be compile. I would suggest moving the files which aren't supposed to be part of the main app itself to a different directory.
