### ISSUE TITLE
Package.json error

### ISSUE THREAD

**Issue by mynameishamish** [spark/particle-dev#224]
I'm getting this error when trying to use particle dev with my Redbear, I'm teaching a class using this board and Particle dev in Atom, and I'm getting this error on about 10% of my students machines when I try to open the Serial Port.

Can any one point me to a solution?

<img width="467" alt="screen_shot_20170907_at_12 02 24_am" src="https://user-images.githubusercontent.com/5396480/30226927-cbac0a14-94a5-11e7-8fc7-d3ab5b0e0034.png">

**Comment by suda** [comment]
Hi Hamish! If you rename `~/.particledev` directory to something else (but not remove it) and start the Desktop IDE again, does it makes the error disappear?

**Comment by mynameishamish** [comment]
That fixed it, thanks!

**Comment by suda** [comment]
That's great! Could you zip the contents of it and send it to me at wojtek@particle.io ?
