### ISSUE TITLE
CLI Compile Not Sending hpp files

### ISSUE THREAD

**Issue by sidwarkd** [spark/particle-dev#227]
The documentation says that the CLI will send *.hpp files to the cloud for compilation but that doesn't appear to be happening. I'm trying to include the ArduinoJson library in a project and when I compile it from the command line I get an error:
`lib/ArduinoJson/src/ArduinoJson.h:10:27: fatal error: ArduinoJson.hpp: No such file or directory
 #include "ArduinoJson.hpp"`

When I look at the list of files sent to the cloud in the output `ArduinoJson.hpp` is not listed despite existing in the folder.

**Comment by suda** [comment]
Hi Kevin. This has been just fixed in [0.2.1 release](https://github.com/spark/particle-dev/releases/tag/v0.2.1) :) If you're using Atom it will notify about the update. We'll update this fix in the next Particle Dev App release soon.
