### ISSUE TITLE
Fully Off-Line Development

### ISSUE THREAD

**Issue by rei-vilo** [spark/particle-dev#27]
Spark Dev based on Atom only allows editing off-line.

However, compilation is done still on the cloud.

Is there any plan to add compilation off-line?

**Comment by suda** [comment]
@rei-vilo @jamesarm97 @romulof @robertdolca we're releasing an alpha version of local compiler: https://github.com/spark/particle-dev-local-compiler

We would love your input on this :)

**Comment by robertdolca** [comment]
@suda great news :)

**Comment by jamesarm97** [comment]
Does the local compile option support online libraries? The one thing I alway missed with the other spark local compiler what the lack of library support. It would be nice to still have it somehow show available libraries and git checkout the files for you.

**Comment by suda** [comment]
It doesn't support automatic libraries download yet (but it is on our roadmap). It does support nested directories, so your project can contain manually downloaded libraries allowing you to use them.

**Comment by rei-vilo** [comment]
I'm stuck at step 11. Choose Particle Dev Local Compiler: Update Firmware Versions.

<img width="474" alt="capture 2015-11-10 a 16 46 50" src="https://cloud.githubusercontent.com/assets/951776/11067415/ace3050c-87cc-11e5-9400-8f78d3df713d.png">

**Comment by robertdolca** [comment]
@rei-vilo it took like 10 minutes and I have a 500 megabit connection

**Comment by rei-vilo** [comment]
Ok, the window closed after 15 minutes.

Now, three problems:

* I have this error message, although the docker-machine is running and `Docker Cert Path` and `Docker Host` have been copied-pasted onto the settings of **Particle Dev Local Compiler**.

<img width="320" alt="capture 2015-11-10 a 17 13 56" src="https://cloud.githubusercontent.com/assets/951776/11067921/3d6074be-87cf-11e5-97f9-275bbb362d16.png">

* My board is listed but not the version.

<img width="309" alt="capture 2015-11-10 a 17 18 13" src="https://cloud.githubusercontent.com/assets/951776/11067908/206b2bce-87cf-11e5-803f-a8a9f00df2e5.png">

* The `VBoxHeadLess` virtual machine takes almost all the power of my MacBook.

I was expecting something light, not a VM!

Cloud build and upload work fine.

**Comment by robertdolca** [comment]
@rei-vilo You can delete your docker-machine and recreate it with less resources. I know it can take allot of resources but this way is easier to run on any platform

**Comment by suda** [comment]
First update may take a long time but consecutive ones will just download missing changes. CPU utilization is also high during update. Single compile does very little after this.

@rei-vilo you can try clicking **Unknown** in the status bar to see list of available versions.

**Comment by rei-vilo** [comment]
Maybe it's worth mentioning the `update firmware` process downloaded 6 GB of data! I'd like to have some feed-back, as per #9.

If I understand correctly, the off-line build process is hosted in a virtual machine under Linux with the whole tool-chain and SDK are inside. 

Is this a temporary solution? Mac OS X is based on Linux, so I don't understand the rationale behind such a solution.

**Comment by robertdolca** [comment]
As far I can see the setup uses Docker wich is a wrapper around Linux Containers (LXC). The compilation is run in a container which is deleted after the binary is copied out. This is a good thing because you don't have to install compilation any tool on your PC. Also all the tools come bundled in a docker image. 

The OS X kernel is not Linux kernel, so it does not have support for LXC. That's why docker-machine created a linux virtual machine where it runs the containers. If you would be on linux you would not need the VM.

**Comment by robertdolca** [comment]
PS: OS X is not based on Linux. It is a certified Unix and it follows the POSIX standard but that's it :)

**Comment by rei-vilo** [comment]
Thank you for the details. Basically, we're running a virtual machine at home like those run by Particle on the cloud.

Let's do the maths: 22 GB for the virtual machine, Docker and Particle Dev. Almost 10% of my SSD. 

That's a lot compared with a more standard approach. 

* The GCC tool-chain is already installed and shared with other boards. 
* The Particle SDK is 27 MB only.
* Not to mention speed.

**Comment by suda** [comment]
Here are some reasons we decided to go with Docker:
- local compiler works on OS X, Windows and Linux without additional development
- build results are always the same no matter the host OS
- we consider using the same Docker images in our cloud compiler which would blur difference between local and cloud making development unified
- contained firmware images solve issues with toolchain version dependencies and allow us to upgrade it without breaking older versions
- [buildpacks](https://github.com/spark/buildpack-base) introduce a unified process for firmware development/release helping us and 3rd party developers bring their devices to our ecosystem

There are definitely some drawbacks compared to installing just the toolchain (like disk requirement, speed penalty) but Docker does solve more problems than it introduces.

What we have here is an **alpha** release. There's much to fix in the future and your feedback helps us decide where to put our energy :)

**Comment by rei-vilo** [comment]
I'd like to use the IDE I'm used at, Xcode. 

Good luck with the development!

**Comment by suda** [comment]
You can still use buildpacks w/o Particle Dev/Atom. We'll update the docs with more command line instructions, so it's easier to plug into your favorite IDE or CI.

**Comment by rei-vilo** [comment]
Thanks!

**Comment by suda** [comment]
Any development of local/offline compilation will be done in (currently not functioning) [`particle-dev-local-compiler`](https://github.com/spark/particle-dev-local-compiler) package thus any discussion should be moved there.
