### ISSUE TITLE
Web IDE/Particle Build seems to treat libraries differently between Core and Photon

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-dev#95]
http://community.particle.io/t/how-to-include-a-library-because-im-failing/12931/8

In this thread @mumblepins found that a lib he ported did build against the Photon but not against Core due to using `#include <....>` instead of `#include "...."`.
The behaviour should be consistent accross platforms.

---

Posted under `Particle Dev` since `Particle Build` doesn't seem to have a place on github ;-)

**Comment by zsup** [comment]
This sounds like a firmware issue rather than an IDE issue; @ScruffR can I ask you to open an issue in `spark/firmware` instead?

**Comment by technobly** [comment]
Pretty sure this would be a compile-service issue with the preprocessor.  This exact issue has come up in the past.  cc: @dmiddlecamp ;-)

**Comment by dmiddlecamp** [comment]
the only difference between these for the build farm is essentially how the makefile treats the library files when they're included in the build, so it's possible something reverted in the newer makefile

**Comment by zsup** [comment]
so if it's a makefile issue then it's a firmware issue, yes?

**Comment by dmiddlecamp** [comment]
I _think_ so, but I could be wrong.  Either way some unit testing on the build farm repo that confirms the desired behavior would be cool, then we can be confident we don't regress, even if we make the change in the firmware repo.

**Comment by ScruffR** [comment]
So if it could be either a FW or an IDE issue (and I'm not in the position to tell), can I ask you Dave to open the FW issue if it turns out to be FW rather than me doing it now and then it turns out it wasn't after all ;-)

**Comment by dmiddlecamp** [comment]
looking back at this, I don't think we supported the `<...>` syntax before, so it sounds like the newer makefile is more forgiving instead of less forgiving, so I think this isn't a regression.  Does that sound right?

**Comment by technobly** [comment]
We used to include <...> some files in the way past, it was actually a thing... and at some point it started failing.  Search won't find things like this, but I looked through some of my old libraries.  Check it out... I know this compiled once upon a time:
https://github.com/technobly/SparkCore-RF24/blob/master/RF24.cpp#L22

**Comment by suda** [comment]
With the arrival of libraries V2, this has been now mitigated.
